//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace OnlineMedicineDonation {
    
    
    public partial class ViewRequests {
        
=======
namespace OnlineMedicineDonation
{


    public partial class ViewRequests
    {

>>>>>>> 1bc938adc5e3fdaf6f7afc812415981829d12477
        /// <summary>
        /// MultiView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.MultiView MultiView1;
<<<<<<< HEAD
        
=======

>>>>>>> 1bc938adc5e3fdaf6f7afc812415981829d12477
        /// <summary>
        /// View1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View View1;
<<<<<<< HEAD
        
=======

>>>>>>> 1bc938adc5e3fdaf6f7afc812415981829d12477
        /// <summary>
        /// GridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView1;
<<<<<<< HEAD
        
=======

>>>>>>> 1bc938adc5e3fdaf6f7afc812415981829d12477
        /// <summary>
        /// View2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View View2;
<<<<<<< HEAD
        
        /// <summary>
        /// cblPaymentOptions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBoxList cblPaymentOptions;
        
        /// <summary>
        /// result control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label result;
        
        /// <summary>
        /// btnDonate control.
=======

        /// <summary>
        /// View3 control.
>>>>>>> 1bc938adc5e3fdaf6f7afc812415981829d12477
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Button btnDonate;
=======
        protected global::System.Web.UI.WebControls.View View3;
>>>>>>> 1bc938adc5e3fdaf6f7afc812415981829d12477
    }
}
